apache/maven-shared-utils

pom.xml
src/test/java/org/apache/maven/shared/utils/OsTest.java

As suggested by @rfscholte in [MSHARED-826](https://issues.apache.org/jira/browse/MSHARED-826): updated to maven-parent:33 and set property `javaVersion` to 7.

[MSHARED-826] Require Java 7

---

src/test/java/org/apache/maven/shared/utils/io/DirectoryScannerTest.java

@michael-o also fixes a couple of FindBugs warnings

[MSHARED-685] assert some things

---

.gitignore
src/main/java/org/apache/maven/shared/utils/io/DirectoryScanner.java
src/test/java/org/apache/maven/shared/utils/io/DirectoryScannerTest.java

@rfscholte see if we can make DirectoryScannerTest pass on Windows

[MSHARED-862] system independent file separator

---

readme.md

docs: Java 7 is the target

---

src/main/java/org/apache/maven/shared/utils/PropertyUtils.java
src/test/java/org/apache/maven/shared/utils/PropertyUtilsTest.java

[MSHARED-866] don't throw a java.lang.Error when reading invalid or corrupt properties files

---

src/main/java/org/apache/maven/shared/utils/io/DirectoryScanner.java
src/main/java/org/apache/maven/shared/utils/io/FileUtils.java
src/main/java/org/apache/maven/shared/utils/io/Java7Support.java
src/test/java/org/apache/maven/shared/utils/io/DirectoryScannerTest.java
src/test/java/org/apache/maven/shared/utils/io/FileUtilsTest.java
src/test/java/org/apache/maven/shared/utils/io/Java7SupportTest.java
src/test/java/org/apache/maven/shared/utils/io/SymlinkTestSetup.java

I believe that Java 7 has been a minimum requirement for almost a year so here's some overdue cleanup:
- Call `java.nio.file.Files` utility methods directly rather than via reflection
- Move `createSymbolicLink()` utility to `FileUtils`
- Deprecate `Java7Support` and call `java.nio.file.Files` methods directly
MSHARED-860

[MSHARED-860] Deprecate unnecessary Java7Support

---

src/main/java/org/apache/maven/shared/utils/io/FileUtils.java
src/test/java/org/apache/maven/shared/utils/io/FileUtilsTest.java

[MSHARED-893] deprecate file methods we don't need in Java 7+

---

src/main/java/org/apache/maven/shared/utils/io/FileUtils.java

[MSHARED-893] deprecate more file methods we don't need in Java 7+

---

src/main/java/org/apache/maven/shared/utils/io/FileUtils.java
src/test/java/org/apache/maven/shared/utils/io/FileUtilsTest.java

@michael-o I think this closes out all the FileUtils methods that can be straight-forwardly replaced in Java 7+.

[MSHARED-893] deprecate more methods and clean up api doc and tests

---

src/main/java/org/apache/maven/shared/utils/ReaderFactory.java
src/main/java/org/apache/maven/shared/utils/WriterFactory.java

@michael-o also updated api doc

[MSHARED-860] deprecate constants that are now available in Java 7+

---

src/main/java/org/apache/maven/shared/utils/StringUtils.java

@michael-o Contrary to previous documentation these methods do not remove all whitespace and control characters, only ASCII whitespace and control characters.

docs: correct API docs for clean and trim

---

src/main/java/org/apache/maven/shared/utils/io/DirectoryScanResult.java
src/main/java/org/apache/maven/shared/utils/io/DirectoryScanner.java
src/main/java/org/apache/maven/shared/utils/io/DirectoryWalkListener.java
src/main/java/org/apache/maven/shared/utils/io/MatchPattern.java
src/main/java/org/apache/maven/shared/utils/io/MatchPatterns.java
src/main/java/org/apache/maven/shared/utils/io/ScanConductor.java
src/main/java/org/apache/maven/shared/utils/io/SelectorUtils.java
src/main/java/org/apache/maven/shared/utils/io/WalkCollector.java
src/test/java/org/apache/maven/shared/utils/io/DirectoryScannerTest.java
src/test/java/org/apache/maven/shared/utils/testhelpers/FileTestHelper.java

[MSHARED-898]  prefer JDK classes to DirectoryScanner

---

src/main/java/org/apache/maven/shared/utils/StringUtils.java

[MSHARED-918] deprecate equals in favor of Objects.equals()

---

src/main/java/org/apache/maven/shared/utils/StringUtils.java

[MSHARED-919] deprecate defaultString since it's now in the JDK

---

src/main/java/org/apache/maven/shared/utils/StringUtils.java

@elharo may I ask for review, please?

Restore space between referenced parameter and its description

---

pom.xml
src/main/java/org/apache/maven/shared/utils/xml/Xpp3DomBuilder.java

remove call to deprecated method

---

src/main/java/org/apache/maven/shared/utils/xml/Xpp3DomBuilder.java
src/test/java/org/apache/maven/shared/utils/xml/Xpp3DomBuilderTest.java

[MSHARED-951] fix exception handling

---

src/main/java/org/apache/maven/shared/utils/cli/CommandLineUtils.java

deprecate methods that have been obsolete since Java 1.5

---

src/main/java/org/apache/maven/shared/utils/cli/Commandline.java

Windows 9X is long dead

---

pom.xml

remove unused plexus dependency

---

pom.xml
src/main/java/org/apache/maven/shared/utils/cli/javatool/AbstractJavaTool.java

https://issues.apache.org/jira/browse/MSHARED-983
The complete container was only here to make use of AbstractLogEnabled
ancient class, that uses ancient logging.
Changes:
* Drop p-c-d
* Reorder deps by scope, test last.

[MSHARED-983] Drop plexus container default

---

src/main/java/org/apache/maven/shared/utils/xml/XmlWriterUtil.java
src/test/java/org/apache/maven/shared/utils/xml/XmlWriterUtilTest.java

@cstamas make XmlWriterUtil platform independent and consistent with its documentation

[MSHARED-985] XmlWriterUtil platform independent and consistent

---

src/main/java/org/apache/maven/shared/utils/io/DirectoryScanner.java
src/test/java/org/apache/maven/shared/utils/io/DirectoryScannerTest.java

As suggested in [MJAR-286](https://issues.apache.org/jira/browse/MJAR-286):
> If this is a misconfigured pom, it should at least give a proper error message.
Thus replacing JVM-thrown NPEx with the one with message.

(doc) Throw more descriptive NPEx

---

src/main/java/org/apache/maven/shared/utils/io/FileUtils.java

Use java.nio.Files.isSameFile() to compare path. Since JDK 12
getCanonicalPath() is not cached anymore and very slow on windows.

[MSHARED-1122] FileUtils: avoid getCanonicalPath()

---

src/main/java/org/apache/maven/shared/utils/StringUtils.java

[MSHARED-1169] deprecate join methods now available in Java 8 String class

---

src/main/java/org/apache/maven/shared/utils/xml/Xpp3DomUtils.java

deprecate a string utility method that doesn't belong in this package, wasn't correctly documented, isn't tested, and is duplicated in 72 other places
@slawekjaranowski

[MSHARED-1172] Deprecate redundant isEmptyString method

---

src/main/java/org/apache/maven/shared/utils/WriterFactory.java

XmlStreamWriter is deprecated so the factory methods that create one should be too.  @hboutemy

Deprecate newXmlWriter

---

src/main/java/org/apache/maven/shared/utils/cli/CommandLineTimeOutException.java
src/main/java/org/apache/maven/shared/utils/cli/CommandLineUtils.java
src/main/java/org/apache/maven/shared/utils/cli/StreamFeeder.java
src/test/java/org/apache/maven/shared/utils/cli/StreamFeederTest.java

If input stream has no more available data
StreamFeeder was block forever

[MSHARED-1072] fix blocking in StreamFeeder

---

src/main/java/org/apache/maven/shared/utils/cli/Commandline.java

MavenInvoker still use it.
... or run release train shared-utils -> maven-invoker -> m-release-p

[MSHARED-1014] Make Commandline.addSystemEnvironment public and deprecated

---

src/main/java/org/apache/maven/shared/utils/xml/Xpp3DomBuilder.java
src/test/java/org/apache/maven/shared/utils/xml/Xpp3DomBuilderTest.java

The alternative fix, which might be less invasive, is to move the trimming into the endElement method.

[MSHARED-953] don't trim

---

src/main/java/org/apache/maven/shared/utils/io/DirectoryScanner.java
src/test/java/org/apache/maven/shared/utils/io/DirectoryScannerTest.java

It took some digging through the PR history to figure this out, but some code paths proved to be vestiges of pre-Java 7 symlink hacks and are no longer needed. The public API and behavior is unchanged by this PR.

remove and cleanup unused code

---

src/main/java/org/apache/maven/shared/utils/Os.java
src/main/java/org/apache/maven/shared/utils/cli/Commandline.java
src/main/java/org/apache/maven/shared/utils/cli/shell/BourneShell.java
src/main/java/org/apache/maven/shared/utils/cli/shell/Shell.java
src/main/java/org/apache/maven/shared/utils/introspection/ClassMap.java
src/main/java/org/apache/maven/shared/utils/introspection/MethodMap.java
src/main/java/org/apache/maven/shared/utils/introspection/ReflectionValueExtractor.java
src/main/java/org/apache/maven/shared/utils/io/FileUtils.java
src/main/java/org/apache/maven/shared/utils/io/MatchPattern.java
src/main/java/org/apache/maven/shared/utils/io/SelectorUtils.java
src/main/java/org/apache/maven/shared/utils/io/WalkCollector.java
src/main/java/org/apache/maven/shared/utils/xml/PrettyPrintXMLWriter.java
src/main/java/org/apache/maven/shared/utils/xml/Xpp3Dom.java
src/main/java/org/apache/maven/shared/utils/xml/Xpp3DomBuilder.java
src/main/java/org/apache/maven/shared/utils/xml/Xpp3DomUtils.java
src/test/java/org/apache/maven/shared/utils/StringUtilsTest.java
src/test/java/org/apache/maven/shared/utils/introspection/ReflectionValueExtractorTest.java
src/test/java/org/apache/maven/shared/utils/io/DirectoryScannerTest.java
src/test/java/org/apache/maven/shared/utils/io/FileUtilsTest.java

As discussed on
- https://github.com/apache/maven-scm/pull/184
- https://issues.apache.org/jira/browse/MNG-6847
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UseDiamondOperator?organizationId=QXBhY2hlIE1hdmVu

[MNG-6847] Use diamond operator

---

pom.xml
src/test/java/org/apache/maven/shared/utils/CaseTest.java

Minor change that removes two dependencies, one direct and one transitive, from the test tree.
In 2025 we can assume that computers know how to display non-ASCII letters like the Turkish dotted I, and that's easier to debug in event of failure than a Unicode escape.

Display Unicode unescaped when test fails
