apache/maven-shared-utils

src/site/apt/index.apt.vm

docs: grammar

---

src/main/java/org/apache/maven/shared/utils/cli/CommandLineUtils.java
src/test/java/org/apache/maven/shared/utils/cli/CommandLineUtilsTest.java

[MSHARED-803] set names on threads

---

pom.xml

docs: fix issues URL

---

pom.xml

docs: this project does have further dependencies

---

pom.xml

update to parent 34

---

src/site/apt/index.apt.vm

@hboutemy 
Maybe we used to, but not anymore.

docs: we don't shade commons-io

---

pom.xml

[MSHARED-891] update to commons-lang 3.8.1

---

src/test/java/org/apache/maven/shared/utils/OsTest.java
src/test/java/org/apache/maven/shared/utils/PathToolTest.java
src/test/java/org/apache/maven/shared/utils/StringUtilsTest.java
src/test/java/org/apache/maven/shared/utils/io/DirectoryScannerTest.java
src/test/java/org/apache/maven/shared/utils/io/FileUtilsTest.java
src/test/java/org/apache/maven/shared/utils/io/IOUtilTest.java
src/test/java/org/apache/maven/shared/utils/logging/AnsiMessageBuilderTest.java
src/test/java/org/apache/maven/shared/utils/logging/MessageUtilsTest.java

[MSHARED-892] modernize tests

---

src/main/java/org/apache/maven/shared/utils/io/IOUtil.java
src/test/java/org/apache/maven/shared/utils/io/IOUtilTest.java

[MSHARED-894] deprecate close methods since we require Java 7+

---

src/main/java/org/apache/maven/shared/utils/io/IOUtil.java

@michael-o also clean up and correct much javadoc

[MSHARED-894] deprecate many easily replaced methods

---

pom.xml

update to Maven core 3.1.0

---

pom.xml
src/test/java/org/apache/maven/shared/utils/CaseTest.java
src/test/java/org/apache/maven/shared/utils/StringUtilsTest.java

only affects tests; no new dependencies in model code

replace deprecated method

---

src/main/java/org/apache/maven/shared/utils/ReaderFactory.java
src/main/java/org/apache/maven/shared/utils/xml/XmlStreamReader.java

[MSHARED-848] deprecate XmlStreamReader

---

src/main/java/org/apache/maven/shared/utils/StringUtils.java

[MSHARED-954] Deprecate platform dependent unifyLineSeparators method

---

src/main/java/org/apache/maven/shared/utils/cli/CommandLineUtils.java

remove unreachable catch block

---

src/main/java/org/apache/maven/shared/utils/cli/Commandline.java

libraries should not communicate directly with the end user

---

src/main/java/org/apache/maven/shared/utils/cli/Commandline.java

clean up comments

---

pom.xml

update to JUnit 4.13.2

---

src/test/java/org/apache/maven/shared/utils/xml/XmlWriterUtilTest.java

avoid reusing fixtures

---

src/main/java/org/apache/maven/shared/utils/xml/XMLEncode.java

@cstamas cleanup large chunks of unused YAGNI code and support accurate exception handling.

cleanup YAGNI code and throw accurate exceptions

---

src/main/java/org/apache/maven/shared/utils/io/MatchPattern.java
src/main/java/org/apache/maven/shared/utils/io/MatchPatterns.java

fix double typo

---

src/main/java/org/apache/maven/shared/utils/io/DirectoryScanner.java

Fix typo in DirectoryScanner.java

---

pom.xml

[MSHARED-1113] Downgrade m-resource-p to 3.1.0

---

src/test/java/org/apache/maven/shared/utils/introspection/ReflectionValueExtractorTest.java

1. Check for presence of exception messages
2. Verify which exceptions are thrown

Clear a couple of TODOs by better testing exceptions

---

src/main/java/org/apache/maven/shared/utils/io/FileUtils.java

still trying to figure out how best to replace these methods completely

[MSHARED-1273] clean up API doc and exceptions

---

src/main/java/org/apache/maven/shared/utils/xml/Xpp3Dom.java

remove vestigial comments

---

src/main/java/org/apache/maven/shared/utils/Os.java
src/main/java/org/apache/maven/shared/utils/ReaderFactory.java
src/main/java/org/apache/maven/shared/utils/StringUtils.java
src/main/java/org/apache/maven/shared/utils/WriterFactory.java
src/main/java/org/apache/maven/shared/utils/io/FileUtils.java
src/main/java/org/apache/maven/shared/utils/logging/PlainMessageBuilder.java
src/main/java/org/apache/maven/shared/utils/xml/XmlWriterUtil.java
src/test/java/org/apache/maven/shared/utils/StringUtilsTest.java

Minor improvement that avoids repeated lookups of system properties and is a little more direct in code

Use caching methods for system properties

---

src/main/java/org/apache/maven/shared/utils/io/DirectoryScanner.java
src/main/java/org/apache/maven/shared/utils/io/FileUtils.java
src/test/java/org/apache/maven/shared/utils/CaseTest.java
src/test/java/org/apache/maven/shared/utils/introspection/ReflectionValueExtractorTest.java

Simpler code, and better performance since Java 1.6
see https://stackoverflow.com/questions/53284214/toarray-with-pre-sized-array

Use empty arrays instead of pre-sized ones

---

.github/ISSUE_TEMPLATE/BUG.yml
.github/ISSUE_TEMPLATE/FEATURE.yml
.github/ISSUE_TEMPLATE/config.yml
.github/workflows/pr-automation.yml
.github/workflows/release-drafter.yml
.github/workflows/stale.yml
README.md
pom.xml

* Release was there
* Milestone created

Enable Github Issues
